# Generated by Django 3.2.12 on 2023-03-28 16:01

from django.db import migrations


def create_default_account_tiers(apps, schema_editor):
    AccountTier = apps.get_model("users", "AccountTier")

    # create basic account tier
    basic_tier = AccountTier(
        name="Basic", thumbnail_sizes="200", original_link=False, expiring_links=False
    )
    basic_tier.save()

    # create premium account tier
    premium_tier = AccountTier(
        name="Premium",
        thumbnail_sizes="200,400",
        original_link=True,
        expiring_links=False,
    )
    premium_tier.save()

    # create enterprise account tier
    enterprise_tier = AccountTier(
        name="Enterprise",
        thumbnail_sizes="200,400",
        original_link=True,
        expiring_links=True,
    )
    enterprise_tier.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_account_tiers),
    ]
