# Generated by Django 3.2.12 on 2023-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_expiringuserimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
