# Generated by Django 3.2.12 on 2023-04-01 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expiringuserimage",
            name="user",
        ),
    ]
